### ISSUE TITLE
请问如何能把默认代码模式设置成python呢？

### ISSUE THREAD

**Issue by iris0329** [evgo2017/typora-theme-orange-heart#3]
默认的代码模式是`text`, 请问如何改成`python`呢？

**Comment by evgo2017** [comment]
@iris0329 这个属于 Typora 功能，主题无法设置，主题只可修改显示样式。可在每次输入代码时，以输入 ` ```python[回车]` 的方式进行，这样不需要每次手动修改模式，其他深度设置的方式暂不清楚。

**Comment by iris0329** [comment]
谢谢
