### ISSUE TITLE
建议：改一下代码块的字体/大小以及注释颜色

### ISSUE THREAD

**Issue by Xiaoven** [evgo2017/typora-theme-orange-heart#4]
个人的使用体验：代码块看起来有点费眼睛，不方便向他人展示。

可能原因：字体过于纤细，字体偏小，注释的灰色和背景的黑色对比度不够大

建议：可以换一种稍微粗一点的字体，或适当调大字体，给注释换一种更亮一点的灰色

以下是本主题与 Github 主题代码块的对比，Github 采用的字体在横向上会更舒展，看起来没那么累；而本主题采用的字体在纵向上更细长

<img width="914" alt="Screen Shot 2021-01-20 at 15 55 08" src="https://user-images.githubusercontent.com/55338943/105144233-e77d2780-5b37-11eb-8ae2-3b82c27f9919.png">

<img width="1268" alt="Screen Shot 2021-01-20 at 15 58 49" src="https://user-images.githubusercontent.com/55338943/105144590-6a05e700-5b38-11eb-9430-f7eed11296b2.png">

**Comment by evgo2017** [comment]
@Xiaoven 感谢建议，提上日程。

**Comment by evgo2017** [comment]
@Xiaoven 你好，首先很抱歉这么久才来回复。其次这一块使用的是 Consolas 字体，Github 也是 Consolas 字体系列。也许是差不多的。
