### ISSUE TITLE
左侧侧边栏建议、代码块微调、标题问题

### ISSUE THREAD

**Issue by icefery** [evgo2017/typora-theme-orange-heart#6]
#### 
> emmm 问题比较多，不好意思哈。主要是看到这个二级标题就特别像公众号里的感觉，自己也下载过很多主题（比如 vue 和 inside 等）然后每次都需要自己改动一点点（比如`max-width`和`font-family`等）。奈何自己没有文化不会 CSS，只能寄希望于作者了

#### 左侧侧边栏建议
> 主题的侧边字体赶紧有点太过紧凑，希望可以参考下 [typora-gitbook-theme](https://github.com/16soundsofsilence/typora-gitbook-theme) 的 Azure 或 Teal 赶紧效果挺好的（未选中状态下黑色再深一丢丢赶紧就更好了）。

> 另外试了一下侧边栏用 Roboto 或 ~~苹方粗体~~ 或 思源黑体 好像会更好看一点。

#### 代码块微调
> 外边距 **稍稍** 有点大，希望可以 **稍稍** 调小一点。

> 感觉默认的 GitHub 代码块配色就挺好的。主要是暗色代码块有些时候不是太清晰（比如命令选项和参数）。

> 不开启折行（自动换行时）代码块下方的拖动条颜色不是太清晰，希望可以调整为主题色

#### 标题问题
> 三级标题跨度：一级标题有点不够大（不过也几乎不用）。三级标题 `1.2rem` 感觉和正文的跨度有点小，希望可以 **稍稍** 调大一点点。作为整体过大的补偿可以 **稍稍** 把默认字体调小一点点。

> 一、二级标题左侧无类似 `h3` 这样的提示。感觉如果要加的话所有标题都加上的话更协调一点。

**Comment by evgo2017** [comment]
@icefery ok, 样式这边会统一去处理。在忙别的，可能得一段时间。

**Comment by icefery** [comment]
> @icefery ok, 样式这边会统一去处理。在忙别的，可能得一段时间。

好的呀，--^-^--

**Comment by evgo2017** [comment]
@icefery 
首先很抱歉这么久回复。

1 侧边栏：
是默认样式，细细看来感觉还可以。
2 代码块微调：
上下边距细看也是可以的。
配色这一块各有各的需求，基本感觉可以。
如果没有自动换行，现在会出现滚动条，是透明的。
3 标题问题：
默认字体已经改为自适应，根据程序->偏好设置->外观->字体大小适应。
标题大小根据一定规律上升设置的，h3目前是1.3rem。
标题除了 h2 有特殊设置外，其他都没有特殊样式。

如果还有兴趣请再讨论。
