### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by strongbigsea** [evgo2017/typora-theme-orange-heart#8]
为什么我标题之类无法正常显示，比如，标题高亮还是黄色，而不是白色。

**Comment by evgo2017** [comment]
@strongbigsea 一是确保主题安装对了。二是能否上图看看？

**Comment by PearlLiu-Dev** [comment]
> 为什么我标题之类无法正常显示，比如，标题高亮还是黄色，而不是白色。

我也是！

**Comment by evgo2017** [comment]
@Pearl520 你好，方便的话上传一下图片，以及提供一下版本号。

**Comment by evgo2017** [comment]
暂时先关闭了。如果还有回馈，一至少升级到最后一个免费版本，二重新安装一下最新版本的主题，三提供图片我看看样式，是否是二级标题文字不是白色。
